default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: your_username
  password: <%= ENV['Y_APP_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: y_app_development

test:
  <<: *default
  database: y_app_test

production:
  <<: *default
  database: y_app_production
  username: y_app
  password: <%= ENV['Y_APP_DATABASE_PASSWORD'] %>
